# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

test_that("importe_les_donnees works", {
expect_equal(importe_les_donnees(date_debut = "2022-01-01", date_fin = "2022-01-02"),"https://opendata.paris.fr/api/v2/catalog/datasets/comptages-routiers-permanents/exports/json?where=t_1h>%3Ddate%272022-01-01%27&where=t_1h<%3Ddate%272022-01-02%27&rows=-1&select=iu_ac%2Clibelle%2Ct_1h%2Cq%2Ck&pretty=false&timezone=UTC")
})
