# WARNING - Generated by {fusen} from /dev/flat_minimal.Rmd: do not edit by hand

#' importe_les_donnees Title
#'
#' @param date_debut une date en format yyyy-mm-dd
#' @param date_fin une date en format yyyy-mm-dd
#'
#' @return une chaine de caractère à coller dans le navigateur pour télécharger les données
#' @export
#'
#' @examples
#' importe_les_donnees(date_debut = "2022-01-01", date_fin = "2022-01-02")
importe_les_donnees <- function(date_debut,date_fin) {
  
goodurl<-paste0("https://opendata.paris.fr/api/v2/catalog/datasets/comptages-routiers-permanents/exports/json?where=t_1h>%3Ddate%27",date_debut,"%27&where=t_1h<%3Ddate%27",date_fin,"%27&rows=-1&select=iu_ac%2Clibelle%2Ct_1h%2Cq%2Ck&pretty=false&timezone=UTC")
return(goodurl)
}
